### ISSUE TITLE
vatin from_string strip

### ISSUE THREAD

**Issue by hiaselhans** [codingjoe/django-vies#160]
https://github.com/codingjoe/django-vies/blob/bbb596b0a7913fbbab61b18b0bc3b387a09bc64d/vies/types.py#L158

could we do a `vat_str = re.sub("\s", "", value) return vat_str[:2],  vat_str[2:]` here? this could also catch leading spaces

**Comment by codingjoe** [comment]
@hiaselhans good point, feel free to open up a PR. Maybe don't use `re.sub` but `str.replace`.  It slightly faster and simpler to read ;)

**Comment by hiaselhans** [comment]
ok, i can do a str.replace(" ", "") but i was thinking about cases like someone typing AT-U71738505, for example..?

**Comment by codingjoe** [comment]
@hiaselhans you have a point, but I don't see how it is related to your initial suggestion.
BTW, did you know, that this package is somewhat discontinued. Some functionality was moved to `django-localflavor`. I'd recommend checking that out, and fix bugs there too if you find any.

**Comment by hiaselhans** [comment]
you are right. \s was not sufficient.
so how about `vat_str = re.sub("[^0-9A-Z]", "", value.upper())`

indeed django-localflavor looks good but i didn't find the vatnr. validation and VIES functionality there...

THANKS!

**Comment by codingjoe** [comment]
Hi @hiaselhans,

You can find the django-localflavor integration here:
https://django-localflavor.readthedocs.io/en/latest/generic/#localflavor.generic.validators.VATINValidator

Regarding your RegEx, I don't think it's wise to just remove everything that isn't within `\w\d`. I don't mind removing white spaces or dashes, but anything beyond that should maybe done front end site.

**Comment by hiaselhans** [comment]
ok. are you fine with `[\s-]` ?
i found the validator in localflavor but not the vies soap validation.
So i will do a small little pull request. thanks for everything!

**Comment by codingjoe** [comment]
@hiaselhans, yes we only merged the verification part. We didn't want to add a soap client to the dependencies of `django-localflavor`, because there was only a hand full of poorly maintained once. Now we have zeep, which is great, but probably still something that would only make it into the extra dependencies of django-localflavors.

**Comment by codingjoe** [comment]
In any case, I am not even so sure, you want to online validation. At least not how I implemented it here, since it requires an external and somewhat unreliable service. So making synchronous validation can take your web form down.

I usually only use the regex verification part from django-localflavors these days.
